<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="0" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-02T13:11:48 IST" name="Default suite" finished-at="2025-03-02T13:12:22 IST" duration-ms="34152">
    <groups>
    </groups>
    <test started-at="2025-03-02T13:11:48 IST" name="Default test" finished-at="2025-03-02T13:12:22 IST" duration-ms="34152">
      <class name="AutomayionTestPage.LoginTest">
        <test-method is-config="true" signature="setUpReport()[pri:0, instance:AutomayionTestPage.LoginTest@1fb700ee]" started-at="2025-03-02T13:11:47 IST" name="setUpReport" finished-at="2025-03-02T13:11:48 IST" duration-ms="674" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpReport -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:AutomayionTestPage.LoginTest@1fb700ee]" started-at="2025-03-02T13:11:50 IST" name="setup" finished-at="2025-03-02T13:11:57 IST" duration-ms="7806" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void AutomayionTestPage.LoginTest.CheckoutProcess(java.lang.String,java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="CheckoutProcess(java.lang.String,java.lang.String,java.lang.String)[pri:2, instance:AutomayionTestPage.LoginTest@1fb700ee]" started-at="2025-03-02T13:11:57 IST" name="CheckoutProcess" data-provider="dataProviderTest2" finished-at="2025-03-02T13:12:01 IST" duration-ms="3847" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[First Name]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Last Name]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[ZIpCOde]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Order confirmation message mismatch! expected [Thank you for your order!] but found [Products]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Order confirmation message mismatch! expected [Thank you for your order!] but found [Products]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at AutomayionTestPage.LoginTest.CheckoutProcess(LoginTest.java:155)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckoutProcess -->
        <test-method is-config="true" signature="teardown(org.testng.ITestResult)[pri:0, instance:AutomayionTestPage.LoginTest@1fb700ee]" started-at="2025-03-02T13:12:01 IST" name="teardown" finished-at="2025-03-02T13:12:01 IST" duration-ms="19" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=CheckoutProcess status=FAILURE method=LoginTest.CheckoutProcess(java.lang.String,java.lang.String,java.lang.String)[pri:2, instance:AutomayionTestPage.LoginTest@1fb700ee] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:AutomayionTestPage.LoginTest@1fb700ee]" started-at="2025-03-02T13:12:01 IST" name="setup" finished-at="2025-03-02T13:12:08 IST" duration-ms="6754" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void AutomayionTestPage.LoginTest.CheckoutProcess(java.lang.String,java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="CheckoutProcess(java.lang.String,java.lang.String,java.lang.String)[pri:2, instance:AutomayionTestPage.LoginTest@1fb700ee]" started-at="2025-03-02T13:12:08 IST" name="CheckoutProcess" data-provider="dataProviderTest2" finished-at="2025-03-02T13:12:12 IST" duration-ms="3668" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[John]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Doe]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[12345]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Order confirmation message mismatch! expected [Thank you for your order!] but found [Products]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Order confirmation message mismatch! expected [Thank you for your order!] but found [Products]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at AutomayionTestPage.LoginTest.CheckoutProcess(LoginTest.java:155)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckoutProcess -->
        <test-method is-config="true" signature="teardown(org.testng.ITestResult)[pri:0, instance:AutomayionTestPage.LoginTest@1fb700ee]" started-at="2025-03-02T13:12:12 IST" name="teardown" finished-at="2025-03-02T13:12:12 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=CheckoutProcess status=FAILURE method=LoginTest.CheckoutProcess(java.lang.String,java.lang.String,java.lang.String)[pri:2, instance:AutomayionTestPage.LoginTest@1fb700ee] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:AutomayionTestPage.LoginTest@1fb700ee]" started-at="2025-03-02T13:12:12 IST" name="setup" finished-at="2025-03-02T13:12:18 IST" duration-ms="6167" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void AutomayionTestPage.LoginTest.CheckoutProcess(java.lang.String,java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="CheckoutProcess(java.lang.String,java.lang.String,java.lang.String)[pri:2, instance:AutomayionTestPage.LoginTest@1fb700ee]" started-at="2025-03-02T13:12:18 IST" name="CheckoutProcess" data-provider="dataProviderTest2" finished-at="2025-03-02T13:12:22 IST" duration-ms="4165" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Alice]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Brown]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[56789]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Order confirmation message mismatch! expected [Thank you for your order!] but found [Products]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Order confirmation message mismatch! expected [Thank you for your order!] but found [Products]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at AutomayionTestPage.LoginTest.CheckoutProcess(LoginTest.java:155)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckoutProcess -->
        <test-method is-config="true" signature="teardown(org.testng.ITestResult)[pri:0, instance:AutomayionTestPage.LoginTest@1fb700ee]" started-at="2025-03-02T13:12:22 IST" name="teardown" finished-at="2025-03-02T13:12:22 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=CheckoutProcess status=FAILURE method=LoginTest.CheckoutProcess(java.lang.String,java.lang.String,java.lang.String)[pri:2, instance:AutomayionTestPage.LoginTest@1fb700ee] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="tearDownReport()[pri:0, instance:AutomayionTestPage.LoginTest@1fb700ee]" started-at="2025-03-02T13:12:23 IST" name="tearDownReport" finished-at="2025-03-02T13:12:24 IST" duration-ms="1365" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownReport -->
      </class> <!-- AutomayionTestPage.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
